// <auto-generated />
namespace TimeMonitor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _20_09_2020v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20_09_2020v1));
        
        string IMigrationMetadata.Id
        {
            get { return "202009200301175_20_09_2020 v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
